# Generated by Django 4.1.13 on 2024-03-26 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):
    dependencies = [
        ("script_synergy", "0003_curator_created_at_curator_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curator",
            name="expertise",
            field=models.TextField(
                default="AI, Machine Learning",
                validators=[
                    django.core.validators.RegexValidator(
                        flags=re.RegexFlag["IGNORECASE"], regex="^[a-z,\\s*]+$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="curator",
            name="hourly_rate",
            field=models.FloatField(default=14.5),
        ),
        migrations.AddField(
            model_name="curator",
            name="name",
            field=models.CharField(default="Jane Doe", max_length=255),
        ),
        migrations.AddField(
            model_name="curator",
            name="payment_id",
            field=models.TextField(default="JaneDoe123"),
        ),
        migrations.AddField(
            model_name="curator",
            name="professional_bio",
            field=models.TextField(default="Curator"),
        ),
        migrations.AddField(
            model_name="curator",
            name="rating",
            field=models.SmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("writer_message", models.TextField(blank=True, null=True)),
                ("curator_message", models.TextField(blank=True, null=True)),
                (
                    "curator_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=-1, message="Please score between 0 and 100"
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=101,
                                message="Please score between 0 and 100",
                            ),
                        ],
                    ),
                ),
                (
                    "_statue",
                    models.SmallIntegerField(
                        choices=[
                            (0, "CURATOR_INVITED"),
                            (1, "CURATOR_ACCEPTED_INVITE"),
                            (2, "DOCUMENT_CURATED"),
                            (3, "CURATOR_DECLINED_INVITE"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="script_synergy.curator",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="script_synergy.writerdocuments",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="script_synergy.writer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
